log:
  level: debug
  disable_sentry: true

db:
  url: "postgres://unverified:unverified@localhost:5467/unverified?sslmode=disable"

amqp:
  topic: "unverified-svc"
  publisher: "amqp://guest:guest@localhost:5672/" #telegram_publisher
  subscriber: "amqp://guest:guest@localhost:5672/" #telegram_receiver

jwt:
  secret: SuPeR SeCrEt PhRaSe
  refresh_life: 6h
  access_life: 10m5s

listener:
  addr: :9008

registrator:
  outer_url: "http://localhost:8000/integrations/orchestrator/modules" #endpoint to register MODULE
  inner_url: "http://localhost:9008/integrations/unverified-svc" #endpoint to MODULE itself
  topic: "unverified" #MODULE topic
  title: "Unverified" #MODULE title
  prefix: ""


cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: unverified-svc
  service_port: 80
